services:
  web:
    build: .
    restart: always
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    env_file:
      - .env
    expose:
      - "8000"
    depends_on:
      - db
  
  db:
    image: postgres:15
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=vagvin
  
  nginx:
    image: nginx:1.25
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles:/var/www/thedarktower/staticfiles
      - ./media:/var/www/thedarktower/media
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  postgres_data: