# Generated by Django 5.2 on 2025-04-28 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('robokassa', 'Robokassa'), ('yookassa', 'YooKassa'), ('heleket', 'Heleket')], max_length=20, verbose_name='Платежная система'),
        ),
    ]
